/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupEquipmentDetail.java
 *
 * Created on 24 Mei 12, 13:47:23
 */

package com.kmn.gui.setup;

import com.kmn.MainApps;
import com.kmn.backend.entity.MMedEquipment;
import com.kmn.backend.jpa.MMedEquipmentJpaController;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author Hermanto
 */
public class SetupEquipmentDetail extends javax.swing.JDialog {
    private MMedEquipmentJpaController equip;
    private List<MMedEquipment> lequip;
    private SetupEquipment setequip;
    private boolean isedit;

    /** Creates new form SetupEquipmentDetail */
    public SetupEquipmentDetail(SetupEquipment setequip, boolean modal, boolean  isedit) {
        super(MainApps.getApplication().getMainFrame(), modal);
        initComponents();

        this.isedit = isedit;
        this.setequip = setequip;
        this.equip = new MMedEquipmentJpaController();
        lequip = (List <MMedEquipment>) this.equip.findMMedEquipmentEntities();

        if(this.equip.getMMedEquipmentCount() < 1) {
            this.comboCode.addItem("No item");
        }
        else {
            for(MMedEquipment lst : lequip)
                this.comboCode.addItem(lst.getEquipmentCode());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCode = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelCom = new javax.swing.JLabel();
        labelSpeed = new javax.swing.JLabel();
        labelDatabits = new javax.swing.JLabel();
        labelParity = new javax.swing.JLabel();
        labelStopbits = new javax.swing.JLabel();
        labelFlowControl = new javax.swing.JLabel();
        comboCode = new javax.swing.JComboBox();
        textName = new javax.swing.JTextField();
        textType = new javax.swing.JTextField();
        textCom = new javax.swing.JTextField();
        comboSpeed = new javax.swing.JComboBox();
        comboData = new javax.swing.JComboBox();
        comboParity = new javax.swing.JComboBox();
        comboStop = new javax.swing.JComboBox();
        comboFlow = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(SetupEquipmentDetail.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelCode.setText(resourceMap.getString("labelCode.text")); // NOI18N
        labelCode.setName("labelCode"); // NOI18N

        labelName.setText(resourceMap.getString("labelName.text")); // NOI18N
        labelName.setName("labelName"); // NOI18N

        labelType.setText(resourceMap.getString("labelType.text")); // NOI18N
        labelType.setName("labelType"); // NOI18N

        labelCom.setText(resourceMap.getString("labelCom.text")); // NOI18N
        labelCom.setName("labelCom"); // NOI18N

        labelSpeed.setText(resourceMap.getString("labelSpeed.text")); // NOI18N
        labelSpeed.setName("labelSpeed"); // NOI18N

        labelDatabits.setText(resourceMap.getString("labelDatabits.text")); // NOI18N
        labelDatabits.setName("labelDatabits"); // NOI18N

        labelParity.setText(resourceMap.getString("labelParity.text")); // NOI18N
        labelParity.setName("labelParity"); // NOI18N

        labelStopbits.setText(resourceMap.getString("labelStopbits.text")); // NOI18N
        labelStopbits.setName("labelStopbits"); // NOI18N

        labelFlowControl.setText(resourceMap.getString("labelFlowControl.text")); // NOI18N
        labelFlowControl.setName("labelFlowControl"); // NOI18N

        comboCode.setName("comboCode"); // NOI18N
        comboCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCodeItemStateChanged(evt);
            }
        });

        textName.setText(resourceMap.getString("textName.text")); // NOI18N
        textName.setEnabled(false);
        textName.setName("textName"); // NOI18N

        textType.setText(resourceMap.getString("textType.text")); // NOI18N
        textType.setEnabled(false);
        textType.setName("textType"); // NOI18N

        textCom.setText(resourceMap.getString("textCom.text")); // NOI18N
        textCom.setName("textCom"); // NOI18N

        comboSpeed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "1200", "2400", "4800", "9600", "19200", "38400", "57600", "115200", "230400", "460800", "921600" }));
        comboSpeed.setName("comboSpeed"); // NOI18N

        comboData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "6", "7", "8" }));
        comboData.setName("comboData"); // NOI18N

        comboParity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Even", "Odd", "None", "Mark", "Space" }));
        comboParity.setName("comboParity"); // NOI18N

        comboStop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1.5", "2" }));
        comboStop.setName("comboStop"); // NOI18N

        comboFlow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Xon / Xoff", "Hardware", "None" }));
        comboFlow.setName("comboFlow"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getActionMap(SetupEquipmentDetail.class, this);
        jButton1.setAction(actionMap.get("addDetail")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("cancelDetail")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCode)
                    .addComponent(labelName)
                    .addComponent(labelType)
                    .addComponent(labelCom)
                    .addComponent(labelSpeed)
                    .addComponent(labelDatabits)
                    .addComponent(labelParity)
                    .addComponent(labelStopbits)
                    .addComponent(labelFlowControl))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addComponent(textType)
                        .addComponent(comboCode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboFlow, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboStop, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboParity, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboData, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboSpeed, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textCom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCode)
                    .addComponent(comboCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(textType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCom)
                    .addComponent(textCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpeed)
                    .addComponent(comboSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDatabits)
                    .addComponent(comboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParity)
                    .addComponent(comboParity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStopbits)
                    .addComponent(comboStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFlowControl)
                    .addComponent(comboFlow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCodeItemStateChanged
        if(this.comboCode.getSelectedItem().equals("No item")) {
            return;
        }
        else {
            for(MMedEquipment lst : lequip) {
                if(lst.getEquipmentCode().equalsIgnoreCase((String) this.comboCode.getSelectedItem())) {
                    this.textName.setText(lst.getName());
                    this.textType.setText(lst.getTypeId().getTypeCode() + " - " + lst.getTypeId().getTypeName());
                    break;
                }
            }
        }
    }//GEN-LAST:event_comboCodeItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCode;
    private javax.swing.JComboBox comboData;
    private javax.swing.JComboBox comboFlow;
    private javax.swing.JComboBox comboParity;
    private javax.swing.JComboBox comboSpeed;
    private javax.swing.JComboBox comboStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelCode;
    private javax.swing.JLabel labelCom;
    private javax.swing.JLabel labelDatabits;
    private javax.swing.JLabel labelFlowControl;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelParity;
    private javax.swing.JLabel labelSpeed;
    private javax.swing.JLabel labelStopbits;
    private javax.swing.JLabel labelType;
    private javax.swing.JTextField textCom;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textType;
    // End of variables declaration//GEN-END:variables

    @Action
    public void cancelDetail() {
        setVisible(false);
    }

    @Action
    public void addDetail() {
        JTable table = setequip.getTabelEquipment();

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{
            (String) comboCode.getSelectedItem(),
            textName.getText(),
            textType.getText(),
            textCom.getText(),
            (String) comboSpeed.getSelectedItem(),
            "",
            ""
        });

        setequip.getListEquipment().add(this);
        setVisible(false);
    }

    public JComboBox getComboCode() {
        return comboCode;
    }

    public JComboBox getComboData() {
        return comboData;
    }

    public JComboBox getComboFlow() {
        return comboFlow;
    }

    public JComboBox getComboParity() {
        return comboParity;
    }

    public JComboBox getComboSpeed() {
        return comboSpeed;
    }

    public JComboBox getComboStop() {
        return comboStop;
    }

    public JTextField getTextCom() {
        return textCom;
    }

    public JTextField getTextName() {
        return textName;
    }

    public JTextField getTextType() {
        return textType;
    }
}
