//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.12 at 01:30:35 PM ICT 
//


package org.springframework.ws.samples.airline.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.springframework.ws.samples.airline.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BookFlightResponse_QNAME = new QName("http://www.springframework.org/spring-ws/samples/airline/schemas/messages", "BookFlightResponse");
    private final static QName _GetFrequentFlyerMileageRequest_QNAME = new QName("http://www.springframework.org/spring-ws/samples/airline/schemas/messages", "GetFrequentFlyerMileageRequest");
    private final static QName _GetFrequentFlyerMileageResponse_QNAME = new QName("http://www.springframework.org/spring-ws/samples/airline/schemas/messages", "GetFrequentFlyerMileageResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.springframework.ws.samples.airline.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Ticket.Passengers }
     * 
     */
    public Ticket.Passengers createTicketPassengers() {
        return new Ticket.Passengers();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.GetFlightsResponse }
     * 
     */
    public GetFlightsResponse createGetFlightsResponse() {
        return new GetFlightsResponse();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.BookFlightRequest.Passengers }
     * 
     */
    public BookFlightRequest.Passengers createBookFlightRequestPassengers() {
        return new BookFlightRequest.Passengers();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.BookFlightRequest }
     * 
     */
    public BookFlightRequest createBookFlightRequest() {
        return new BookFlightRequest();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.GetFlightsRequest }
     * 
     */
    public GetFlightsRequest createGetFlightsRequest() {
        return new GetFlightsRequest();
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link org.springframework.ws.samples.airline.schema.Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Ticket }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", name = "BookFlightResponse")
    public JAXBElement<Ticket> createBookFlightResponse(Ticket value) {
        return new JAXBElement<Ticket>(_BookFlightResponse_QNAME, Ticket.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", name = "GetFrequentFlyerMileageRequest")
    public JAXBElement<String> createGetFrequentFlyerMileageRequest(String value) {
        return new JAXBElement<String>(_GetFrequentFlyerMileageRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", name = "GetFrequentFlyerMileageResponse")
    public JAXBElement<Integer> createGetFrequentFlyerMileageResponse(Integer value) {
        return new JAXBElement<Integer>(_GetFrequentFlyerMileageResponse_QNAME, Integer.class, null, value);
    }

}
