//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.12 at 01:30:35 PM ICT 
//


package org.springframework.ws.samples.airline.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="flightNumber" type="{http://www.springframework.org/spring-ws/samples/airline/schemas/types}FlightNumber"/>
 *         &lt;element name="departureTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="passengers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="9">
 *                   &lt;element name="passenger" type="{http://www.springframework.org/spring-ws/samples/airline/schemas/types}Name"/>
 *                   &lt;element name="username" type="{http://www.springframework.org/spring-ws/samples/airline/schemas/types}FrequentFlyerUsername"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "BookFlightRequest", namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages")
public class BookFlightRequest {

    @XmlElement(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", required = true)
    protected String flightNumber;
    @XmlElement(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar departureTime;
    @XmlElement(namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", required = true)
    protected Passengers passengers;

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setDepartureTime(XMLGregorianCalendar value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * @return
     *     possible object is
     *     {@link org.springframework.ws.samples.airline.schema.BookFlightRequest.Passengers }
     *     
     */
    public Passengers getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.springframework.ws.samples.airline.schema.BookFlightRequest.Passengers }
     *     
     */
    public void setPassengers(Passengers value) {
        this.passengers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="9">
     *         &lt;element name="passenger" type="{http://www.springframework.org/spring-ws/samples/airline/schemas/types}Name"/>
     *         &lt;element name="username" type="{http://www.springframework.org/spring-ws/samples/airline/schemas/types}FrequentFlyerUsername"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passengerOrUsername"
    })
    public static class Passengers {

        @XmlElements({
            @XmlElement(name = "username", namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", type = String.class),
            @XmlElement(name = "passenger", namespace = "http://www.springframework.org/spring-ws/samples/airline/schemas/messages", type = Name.class)
        })
        protected List<Object> passengerOrUsername;

        /**
         * Gets the value of the passengerOrUsername property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerOrUsername property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerOrUsername().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link Name }
         * 
         * 
         */
        public List<Object> getPassengerOrUsername() {
            if (passengerOrUsername == null) {
                passengerOrUsername = new ArrayList<Object>();
            }
            return this.passengerOrUsername;
        }

    }

}
