package id.co.kmn.backend.model;

/**
 * @author <a href="valeo.gumilang@gmail.com">Valeo Gumilang</a>
 * @Date 5/1/12
 * Time: 11:34 AM
 */
import java.util.Date;

/**
 * Muniv generated by hbm2java
 */
public class Mmedproducer implements java.io.Serializable {


     private int id;
     private String prodCode;
     private String prodName;
     private String activeSts;
     private Date createDate;
     private String creatorId;
     private Date lastUpdate;
     private String lastUserId;

    public Mmedproducer() {
    }


    public Mmedproducer(int id, String prodCode, String prodName, String activeSts) {
        this.id = id;
        this.prodCode = prodCode;
        this.prodName = prodName;
        this.activeSts = activeSts;
    }
    public Mmedproducer(int id, String prodCode, String prodName, String activeSts, Date createDate, String creatorId, Date lastUpdate, String lastUserId) {
       this.id = id;
       this.prodCode = prodCode;
       this.prodName = prodName;
       this.activeSts = activeSts;
       this.createDate = createDate;
       this.creatorId = creatorId;
       this.lastUpdate = lastUpdate;
       this.lastUserId = lastUserId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }
    public String getProdName() {
        return this.prodName;
    }

    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    public String getActiveSts() {
        return this.activeSts;
    }

    public void setActiveSts(String activeSts) {
        this.activeSts = activeSts;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getLastUserId() {
        return this.lastUserId;
    }

    public void setLastUserId(String lastUserId) {
        this.lastUserId = lastUserId;
    }
}
