//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.12 at 01:30:35 PM ICT 
//


package org.springframework.ws.samples.airline.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="economy"/>
 *     &lt;enumeration value="business"/>
 *     &lt;enumeration value="first"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceClass")
@XmlEnum
public enum ServiceClass {

    @XmlEnumValue("economy")
    ECONOMY("economy"),
    @XmlEnumValue("business")
    BUSINESS("business"),
    @XmlEnumValue("first")
    FIRST("first");
    private final String value;

    ServiceClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceClass fromValue(String v) {
        for (ServiceClass c: ServiceClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
