/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenDialog.java
 *
 * Created on 27 Mei 12, 18:43:01
 */

package com.kmn.gui.workspace;

import com.kmn.MainApps;
import com.kmn.MainView;
import com.kmn.controller.Confirm;
import com.kmn.controller.props.EquipmentDetailProperties;
import com.kmn.controller.props.EquipmentProperties;
import java.util.List;
import javax.swing.JTabbedPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Hermanto
 */
public class OpenDialog extends javax.swing.JDialog implements Confirm {
    private EquipmentProperties propEuipment = new EquipmentProperties(this);
    private AddNewWorkspace newWorkspace = new AddNewWorkspace(this);
    private MainView mainView;

    /** Creates new form OpenDialog */
    public OpenDialog(MainView mainview, boolean modal) {
        super(MainApps.getApplication().getMainFrame(), modal);
        this.mainView = mainview;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOpen = new javax.swing.JLabel();
        comboEquip = new javax.swing.JComboBox();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(OpenDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelOpen.setText(resourceMap.getString("labelOpen.text")); // NOI18N
        labelOpen.setName("labelOpen"); // NOI18N

        comboEquip.setName("comboEquip"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getActionMap(OpenDialog.class, this);
        buttonOk.setAction(actionMap.get("openNewWorkspace")); // NOI18N
        buttonOk.setIcon(resourceMap.getIcon("buttonOk.icon")); // NOI18N
        buttonOk.setText(resourceMap.getString("buttonOk.text")); // NOI18N
        buttonOk.setName("buttonOk"); // NOI18N

        buttonCancel.setAction(actionMap.get("cancelOpen")); // NOI18N
        buttonCancel.setIcon(resourceMap.getIcon("buttonCancel.icon")); // NOI18N
        buttonCancel.setText(resourceMap.getString("buttonCancel.text")); // NOI18N
        buttonCancel.setToolTipText(resourceMap.getString("buttonCancel.toolTipText")); // NOI18N
        buttonCancel.setName("buttonCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOpen)
                        .addGap(18, 18, 18)
                        .addComponent(comboEquip, 0, 231, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancel)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOpen)
                    .addComponent(comboEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonCancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        propEuipment.load();
        List<EquipmentDetailProperties> listEuip = propEuipment.getListDetailEquipment();

        for(EquipmentDetailProperties equip : listEuip) {
            String code = equip.getCode() +" - "+ equip.getName();
            comboEquip.addItem(code);
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox comboEquip;
    private javax.swing.JLabel labelOpen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSuccess() {
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(OpenDialog.class);
        
        String title = (String) comboEquip.getSelectedItem();
        JTabbedPane tab = mainView.getTabMain();
        
        WorkspaceModel model = new WorkspaceModel();
        tab.addTab(title, resourceMap.getIcon("file.tabIcon"),  model);
        tab.setSelectedIndex(tab.getTabCount()-1);

        setVisible(false);
    }

    @Override
    public void onWarning(String message) {
    }

    @Override
    public void onError(Throwable t) {
    }

    @Action
    public void cancelOpen() {
        setVisible(false);
    }

    @Action
    public void openNewWorkspace() {
        newWorkspace.add();
    }

}
