CONNECT TO SIAK;
ALTER TABLE SIAK.MDETILKURIKULUM ADD CONSTRAINT FK_DET_KURIKULUM FOREIGN KEY (KURIKULUM_ID) REFERENCES SIAK.MKURIKULUM (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION ;
CONNECT RESET;
