CONNECT TO SIAK;
ALTER TABLE SIAK.MKURIKULUM ADD CONSTRAINT FK_KUR_PEMINATAN FOREIGN KEY (PEMINATAN_ID) REFERENCES SIAK.MPEMINATAN (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION ;
CONNECT RESET;
