package id.co.kmn.backend.model;

/**
 * @author <a href="valeo.gumilang@gmail.com">Valeo Gumilang</a>
 * @Date 5/1/12
 * Time: 11:34 AM
 */
import java.util.Date;

/**
 * Muniv generated by hbm2java
 */
public class Mmedroom implements java.io.Serializable {


     private int id;
     private String roomCode;
     private String roomName;
     private String description;
     private String activeSts;
     private Date createDate;
     private String creatorId;
     private Date lastUpdate;
     private String lastUserId;

    public Mmedroom() {
    }

    public Mmedroom(int id, String roomCode, String roomName, String description, String activeSts) {
        this.id = id;
        this.roomCode = roomCode;
        this.roomName = roomName;
        this.description = description;
        this.activeSts = activeSts;
    }

    public Mmedroom(int id, String roomCode, String roomName, String description, String activeSts, Date createDate, String creatorId, Date lastUpdate, String lastUserId) {
       this.id = id;
       this.roomCode = roomCode;
       this.roomName = roomName;
       this.description = description;
       this.activeSts = activeSts;
       this.createDate = createDate;
       this.creatorId = creatorId;
       this.lastUpdate = lastUpdate;
       this.lastUserId = lastUserId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRoomCode() {
        return this.roomCode;
    }

    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }

    public String getRoomName() {
        return this.roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getActiveSts() {
        return this.activeSts;
    }

    public void setActiveSts(String activeSts) {
        this.activeSts = activeSts;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getLastUserId() {
        return this.lastUserId;
    }

    public void setLastUserId(String lastUserId) {
        this.lastUserId = lastUserId;
    }
}
