/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupDatabase.java
 *
 * Created on 23 Mei 12, 23:54:40
 */

package com.kmn.gui.setup;

import com.kmn.MainApps;
import com.kmn.MainView;
import com.kmn.controller.Confirm;
import com.kmn.controller.props.DatabaseProperties;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Hermanto
 */
public class SetupDatabase extends javax.swing.JDialog implements Confirm {
    private DatabaseProperties dbprop = new DatabaseProperties(this);

    /** Creates new form SetupDatabase */
    public SetupDatabase(MainView mainview, boolean modal) {
        super(MainApps.getApplication().getMainFrame(), modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconDb = new javax.swing.JLabel();
        labelDb = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelDriver = new javax.swing.JLabel();
        labelUrl = new javax.swing.JLabel();
        labelProvider = new javax.swing.JLabel();
        textUserName = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        textDriver = new javax.swing.JTextField();
        textUrl = new javax.swing.JTextField();
        textProvider = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(SetupDatabase.class);
        setTitle(resourceMap.getString("formDbSetup.title")); // NOI18N
        setName("formDbSetup"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        iconDb.setIcon(resourceMap.getIcon("iconDb.icon")); // NOI18N
        iconDb.setText(resourceMap.getString("iconDb.text")); // NOI18N
        iconDb.setName("iconDb"); // NOI18N

        labelDb.setFont(resourceMap.getFont("labelDb.font")); // NOI18N
        labelDb.setText(resourceMap.getString("labelDb.text")); // NOI18N
        labelDb.setName("labelDb"); // NOI18N

        labelUserName.setText(resourceMap.getString("labelUserName.text")); // NOI18N
        labelUserName.setName("labelUserName"); // NOI18N

        labelPassword.setText(resourceMap.getString("labelPassword.text")); // NOI18N
        labelPassword.setName("labelPassword"); // NOI18N

        labelDriver.setText(resourceMap.getString("labelDriver.text")); // NOI18N
        labelDriver.setName("labelDriver"); // NOI18N

        labelUrl.setText(resourceMap.getString("labelUrl.text")); // NOI18N
        labelUrl.setName("labelUrl"); // NOI18N

        labelProvider.setText(resourceMap.getString("labelProvider.text")); // NOI18N
        labelProvider.setName("labelProvider"); // NOI18N

        textUserName.setText(resourceMap.getString("textUserName.text")); // NOI18N
        textUserName.setName("textUserName"); // NOI18N

        textPassword.setText(resourceMap.getString("textPassword.text")); // NOI18N
        textPassword.setName("textPassword"); // NOI18N

        textDriver.setText(resourceMap.getString("textDriver.text")); // NOI18N
        textDriver.setName("textDriver"); // NOI18N

        textUrl.setText(resourceMap.getString("textUrl.text")); // NOI18N
        textUrl.setName("textUrl"); // NOI18N

        textProvider.setText(resourceMap.getString("textProvider.text")); // NOI18N
        textProvider.setName("textProvider"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getActionMap(SetupDatabase.class, this);
        buttonSave.setAction(actionMap.get("saveSetupDB")); // NOI18N
        buttonSave.setIcon(resourceMap.getIcon("buttonSave.icon")); // NOI18N
        buttonSave.setText(resourceMap.getString("buttonSave.text")); // NOI18N
        buttonSave.setName("buttonSave"); // NOI18N

        buttonCancel.setAction(actionMap.get("closeSetupDB")); // NOI18N
        buttonCancel.setIcon(resourceMap.getIcon("buttonCancel.icon")); // NOI18N
        buttonCancel.setText(resourceMap.getString("buttonCancel.text")); // NOI18N
        buttonCancel.setName("buttonCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconDb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserName)
                            .addComponent(labelPassword)
                            .addComponent(labelDriver)
                            .addComponent(labelUrl)
                            .addComponent(labelProvider))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textProvider)
                            .addComponent(textUrl)
                            .addComponent(textDriver)
                            .addComponent(textPassword)
                            .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelDb))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(buttonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconDb)
                    .addComponent(labelDb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserName)
                    .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDriver)
                    .addComponent(textDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUrl)
                    .addComponent(textUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProvider)
                    .addComponent(textProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dbprop.load();
        this.textUserName.setText(dbprop.getUsername());
        this.textPassword.setText(dbprop.getPassword());
        this.textDriver.setText(dbprop.getDriver());
        this.textUrl.setText(dbprop.getUrl());
        this.textProvider.setText(dbprop.getProvider());
    }//GEN-LAST:event_formWindowOpened

    @Action
    public void closeSetupDB() {
        setVisible(false);
    }

    @Action
    public void saveSetupDB() {
        dbprop.setUsername(this.textUserName.getText());
        dbprop.setPassword(this.textPassword.getText());
        dbprop.setDriver(this.textDriver.getText());
        dbprop.setUrl(this.textUrl.getText());
        dbprop.setProvider(this.textProvider.getText());
        dbprop.store();
        
        setVisible(false);
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel iconDb;
    private javax.swing.JLabel labelDb;
    private javax.swing.JLabel labelDriver;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelProvider;
    private javax.swing.JLabel labelUrl;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JTextField textDriver;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textProvider;
    private javax.swing.JTextField textUrl;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables

    //@Override
    public void onSuccess() {
        setVisible(false);
    }

    //@Override
    public void onWarning(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    //@Override
    public void onError(Throwable t) {
        JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
