/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupServer.java
 *
 * Created on 24 Mei 12, 2:42:02
 */

package com.kmn.gui.setup;

import com.kmn.MainApps;
import com.kmn.MainView;
import com.kmn.controller.Confirm;
import com.kmn.controller.props.ServerProperties;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Hermanto
 */
public class SetupServer extends javax.swing.JDialog implements Confirm {
    private ServerProperties svprop = new ServerProperties(this);

    /** Creates new form SetupServer */
    public SetupServer(MainView mainview, boolean modal) {
        super(MainApps.getApplication().getMainFrame(), modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconServer = new javax.swing.JLabel();
        labelServer = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelIp = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        textUserName = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        textIp = new javax.swing.JTextField();
        textPort = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(SetupServer.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        iconServer.setIcon(resourceMap.getIcon("iconServer.icon")); // NOI18N
        iconServer.setText(resourceMap.getString("iconServer.text")); // NOI18N
        iconServer.setName("iconServer"); // NOI18N

        labelServer.setFont(resourceMap.getFont("labelServer.font")); // NOI18N
        labelServer.setText(resourceMap.getString("labelServer.text")); // NOI18N
        labelServer.setName("labelServer"); // NOI18N

        labelUserName.setText(resourceMap.getString("labelUserName.text")); // NOI18N
        labelUserName.setName("labelUserName"); // NOI18N

        labelPassword.setText(resourceMap.getString("labelPassword.text")); // NOI18N
        labelPassword.setName("labelPassword"); // NOI18N

        labelIp.setText(resourceMap.getString("labelIp.text")); // NOI18N
        labelIp.setName("labelIp"); // NOI18N

        labelPort.setText(resourceMap.getString("labelPort.text")); // NOI18N
        labelPort.setName("labelPort"); // NOI18N

        textUserName.setText(resourceMap.getString("textUserName.text")); // NOI18N
        textUserName.setName("textUserName"); // NOI18N

        textPassword.setText(resourceMap.getString("textPassword.text")); // NOI18N
        textPassword.setName("textPassword"); // NOI18N

        textIp.setText(resourceMap.getString("textIp.text")); // NOI18N
        textIp.setName("textIp"); // NOI18N

        textPort.setText(resourceMap.getString("textPort.text")); // NOI18N
        textPort.setName("textPort"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getActionMap(SetupServer.class, this);
        jButton1.setAction(actionMap.get("closeSetupServer")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("saveSetupServer")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelServer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserName)
                            .addComponent(labelPassword)
                            .addComponent(labelIp)
                            .addComponent(labelPort))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textPort)
                                .addComponent(textIp)
                                .addComponent(textUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelServer)
                    .addComponent(iconServer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserName)
                    .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        svprop.load();
        this.textUserName.setText(svprop.getUsername());
        this.textPassword.setText(svprop.getPassword());
        this.textIp.setText(svprop.getIp());
        this.textPort.setText(svprop.getPort());
    }//GEN-LAST:event_formWindowOpened

    @Action
    public void closeSetupServer() {
        setVisible(false);
    }

    @Action
    public void saveSetupServer() {
        svprop.setUsername(this.textUserName.getText());
        svprop.setPassword(this.textPassword.getText());
        svprop.setIp(this.textIp.getText());
        svprop.setPort(this.textPort.getText());
        svprop.store();

        setVisible(false);

        int confirm = JOptionPane.showConfirmDialog(this,
                "You must restart application for the changes to take effect", "Restart", 2);
        if(confirm == 0) MainApps.getApplication().close();
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconServer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelIp;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelServer;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JTextField textIp;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textPort;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables

    //@Override
    public void onSuccess() {
        setVisible(false);
    }

    //@Override
    public void onWarning(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    //@Override
    public void onError(Throwable t) {
        JOptionPane.showMessageDialog(this, t.getMessage());
    }

}
