/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupEquipment.java
 *
 * Created on 24 Mei 12, 3:18:10
 */

package com.kmn.gui.setup;

import com.kmn.MainApps;
import com.kmn.MainView;
import com.kmn.controller.Confirm;
import com.kmn.controller.props.EquipmentDetailProperties;
import com.kmn.controller.props.EquipmentProperties;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author Hermanto
 */
public class SetupEquipment extends javax.swing.JDialog implements Confirm {
    private SetupEquipmentDetail detailBox;
    private List<SetupEquipmentDetail> listEquipment = new ArrayList<SetupEquipmentDetail>();
    private EquipmentProperties eqprop = new EquipmentProperties(this);;
    
        /** Creates new form SetupEquipment */
    public SetupEquipment(MainView mainview, boolean modal) {
        super(MainApps.getApplication().getMainFrame(), modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        iconEquipment = new javax.swing.JLabel();
        labelEquipment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEquipment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getResourceMap(SetupEquipment.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.kmn.MainApps.class).getContext().getActionMap(SetupEquipment.class, this);
        buttonAdd.setAction(actionMap.get("openDetail")); // NOI18N
        buttonAdd.setText(resourceMap.getString("buttonAdd.text")); // NOI18N
        buttonAdd.setName("buttonAdd"); // NOI18N

        buttonEdit.setAction(actionMap.get("editDetail")); // NOI18N
        buttonEdit.setText(resourceMap.getString("buttonEdit.text")); // NOI18N
        buttonEdit.setName("buttonEdit"); // NOI18N

        buttonRemove.setText(resourceMap.getString("buttonRemove.text")); // NOI18N
        buttonRemove.setName("buttonRemove"); // NOI18N

        buttonCancel.setAction(actionMap.get("closeSetupEquipment")); // NOI18N
        buttonCancel.setText(resourceMap.getString("buttonCancel.text")); // NOI18N
        buttonCancel.setName("buttonCancel"); // NOI18N

        buttonSave.setAction(actionMap.get("saveSetupEquipment")); // NOI18N
        buttonSave.setText(resourceMap.getString("buttonSave.text")); // NOI18N
        buttonSave.setName("buttonSave"); // NOI18N

        iconEquipment.setIcon(resourceMap.getIcon("iconEquipment.icon")); // NOI18N
        iconEquipment.setText(resourceMap.getString("iconEquipment.text")); // NOI18N
        iconEquipment.setName("iconEquipment"); // NOI18N

        labelEquipment.setFont(resourceMap.getFont("labelEquipment.font")); // NOI18N
        labelEquipment.setText(resourceMap.getString("labelEquipment.text")); // NOI18N
        labelEquipment.setName("labelEquipment"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabelEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Type", "Com", "Bound Rate", "IP", "Port"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelEquipment.setName("tabelEquipment"); // NOI18N
        jScrollPane1.setViewportView(tabelEquipment);
        tabelEquipment.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title0")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title1")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title2")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title3")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title4")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title5")); // NOI18N
        tabelEquipment.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("tabelEquipment.columnModel.title6")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconEquipment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEquipment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconEquipment)
                    .addComponent(labelEquipment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemove))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        eqprop.load();
        List<EquipmentDetailProperties> eqList = eqprop.getEqList();
        
        DefaultTableModel model = (DefaultTableModel) tabelEquipment.getModel();
        for(EquipmentDetailProperties ql : eqList) {
            model.addRow(new Object[]{
                (String) ql.getCode(),
                ql.getName(),
                ql.getType(),
                ql.getCom(),
                ql.getRate(),
                "",
                ""
            });
        }
    }//GEN-LAST:event_formWindowOpened

    @Action
    public void closeSetupEquipment() {
        setVisible(false);
    }

    @Action
    public void openDetail() {
        if (detailBox == null) {
            JFrame mainFrame = MainApps.getApplication().getMainFrame();
            detailBox = new SetupEquipmentDetail(this, true, false);
            detailBox.setLocationRelativeTo(this);
        }
        MainApps.getApplication().show(detailBox);
    }

    @Action
    public void editDetail() {
        if (detailBox == null) {
            JFrame mainFrame = MainApps.getApplication().getMainFrame();
            detailBox = new SetupEquipmentDetail(this, true, true);
            detailBox.setLocationRelativeTo(this);
        }
        MainApps.getApplication().show(detailBox);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel iconEquipment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEquipment;
    private javax.swing.JTable tabelEquipment;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelEquipment() {
        return tabelEquipment;
    }

    @Action
    public void saveSetupEquipment() {
        boolean isnew = false;
        for(SetupEquipmentDetail detail : listEquipment) {
            String uniqcode = (String) detail.getComboCode().getSelectedItem();
            
            eqprop.setEqcode(uniqcode);
            EquipmentDetailProperties detalprop = eqprop.getDetalProperies(uniqcode);
            if(detalprop == null) {
                isnew = true;
                detalprop = new EquipmentDetailProperties(uniqcode);
            }
            
            detalprop.setCode((String)detail.getComboCode().getSelectedItem());
            detalprop.setName(detail.getTextName().getText());
            detalprop.setType(detail.getTextType().getText());
            detalprop.setCom(detail.getTextCom().getText());
            detalprop.setRate((String) detail.getComboSpeed().getSelectedItem());
            detalprop.setDataBit((String) detail.getComboData().getSelectedItem());
            detalprop.setParity((String) detail.getComboParity().getSelectedItem());
            detalprop.setStopBit((String) detail.getComboStop().getSelectedItem());
            detalprop.setFlow((String) detail.getComboFlow().getSelectedItem());
            detalprop.setIp("");
            detalprop.setPort("");
            
            if(isnew) eqprop.addDetalProperies(detalprop);
        }
        
        eqprop.store();
        setVisible(false);
    }

    public List getListEquipment() {
        return listEquipment;
    }

    @Override
    public void onSuccess() {
        setVisible(false);
    }

    @Override
    public void onWarning(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void onError(Throwable t) {
        JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
