CONNECT TO SIAK;

ALTER TABLE MKURIKULUM ADD COLUMN PEMINATAN_ID INTEGER;

ALTER TABLE MKURIKULUM ADD CONSTRAINT FK_KUR_PEMINATAN FOREIGN KEY (PEMINATAN_ID) REFERENCES MPEMINATAN (ID);


CALL SYSPROC.ALTOBJ ( 'APPLY_CONTINUE_ON_ERROR', 'CREATE TABLE SIAK.MDETILKURIKULUM ( ID INTEGER  NOT NULL , KURIKULUM_ID INTEGER  NOT NULL , PRODI_ID INTEGER  NOT NULL , CCOHORT VARCHAR (6) , MATAKULIAH_ID INTEGER , CJENIS VARCHAR (1) , CSTATUS VARCHAR (1) , CMUN VARCHAR (1) , CLINTASPRODI VARCHAR (1) , CTERMSMT VARCHAR (1) , DCREATEDDATE DATE , CCREATEDBY VARCHAR (10) , DUPDATEDDATE DATE , CUPDATEDBY VARCHAR (10)   ) IN USERSPACE1 ', -1, ? );

ALTER TABLE MDETILKURIKULUM ADD CONSTRAINT FK_DET_KURIKULUM FOREIGN KEY (KURIKULUM_ID) REFERENCES MKURIKULUM (ID);

CONNECT RESET;