DROP TABLE THISTKERJA;
CREATE TABLE THISTKERJA (
		ID INTEGER NOT NULL,
		CTERM CHAR(4),
		SEKOLAH_ID INTEGER ,
		PRODI_ID INTEGER ,
		CNIM CHAR(12) ,
		ALUMNI_ID INTEGER NOT NULL,
		NNOURUT INTEGER NOT NULL,
		CJNSINSTANSI CHAR(1) NOT NULL,
		CNMINSTANSI VARCHAR(50) NOT NULL,
		CALINSTANSI VARCHAR(100) NOT NULL,
		BID_USH_INS_ID INTEGER NOT NULL,
		CKDKERJA CHAR(2),
		CKDGAJI CHAR(2),
		CCREATEDBY VARCHAR(35),
		CCREATEDDATE DATE,
		CUPDATEDBY VARCHAR(35),
		CUPDATEDDATE DATE
	);
CREATE UNIQUE INDEX PK_HISTORY ON THISTKERJA (ID ASC);
--CREATE UNIQUE INDEX UN_HISKERJA ON THISTKERJA (CTERM ASC, SEKOLAH_ID ASC, PRODI_ID ASC, CNIM ASC, NNOURUT ASC);
ALTER TABLE THISTKERJA ADD CONSTRAINT PK_HISTORY PRIMARY KEY (ID);
--ALTER TABLE THISTKERJA ADD CONSTRAINT FK_SEKOLAH FOREIGN KEY (SEKOLAH_ID)
--	REFERENCES MSEKOLAH (ID);
--ALTER TABLE THISTKERJA ADD CONSTRAINT FK_THISTKERJA_PRODI FOREIGN KEY (PRODI_ID)
--	REFERENCES MPRODI (ID);
ALTER TABLE THISTKERJA ADD CONSTRAINT FK_BIDUSAHA FOREIGN KEY (BID_USH_INS_ID)
	REFERENCES MBIDANGUSAHA (ID);

CREATE SEQUENCE MBIDANGUSAHA_SEQ INCREMENT BY 1 START WITH 100000;
CREATE SEQUENCE THISTKERJA_SEQ INCREMENT BY 1 START WITH 100000; 
ALTER TABLE THISTKERJA ADD CONSTRAINT UN_HISTKERJA UNIQUE ( ALUMNI_ID, NNOURUT) ;

INSERT INTO MBIDANGUSAHA (ID,CBIDUSHINS,CNMBIDUSAHA) VALUES (1,'TL','TELEKOMUNIKASI');
INSERT INTO MBIDANGUSAHA (ID,CBIDUSHINS,CNMBIDUSAHA) VALUES (2,'TR','TRANSFORTASI');
COMMIT;

