
package id.co.kmn.services.wsdl.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IntegrasiAlat", targetNamespace = "http://192.168.13.10:2221/apps/kmn/IntegrasiAlat/", wsdlLocation = "http://localhost:9999/apps/kmn/IntegrasiAlat.wsdl")
public class IntegrasiAlat_Service
    extends Service
{

    private final static URL INTEGRASIALAT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(id.co.kmn.services.wsdl.client.IntegrasiAlat_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = id.co.kmn.services.wsdl.client.IntegrasiAlat_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/apps/kmn/IntegrasiAlat.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/apps/kmn/IntegrasiAlat.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTEGRASIALAT_WSDL_LOCATION = url;
    }

    public IntegrasiAlat_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrasiAlat_Service() {
        super(INTEGRASIALAT_WSDL_LOCATION, new QName("http://192.168.13.10:2221/apps/kmn/IntegrasiAlat/", "IntegrasiAlat"));
    }

    /**
     * 
     * @return
     *     returns IntegrasiAlat
     */
    @WebEndpoint(name = "IntegrasiAlatSOAP")
    public IntegrasiAlat getIntegrasiAlatSOAP() {
        return super.getPort(new QName("http://192.168.13.10:2221/apps/kmn/IntegrasiAlat/", "IntegrasiAlatSOAP"), IntegrasiAlat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrasiAlat
     */
    @WebEndpoint(name = "IntegrasiAlatSOAP")
    public IntegrasiAlat getIntegrasiAlatSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://192.168.13.10:2221/apps/kmn/IntegrasiAlat/", "IntegrasiAlatSOAP"), IntegrasiAlat.class, features);
    }

}
